# Generated by Django 5.2.6 on 2025-10-02 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_iniciados', to=settings.AUTH_USER_MODEL)),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creado'],
                'unique_together': {('usuario_emisor', 'usuario_receptor')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_enviado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.chat')),
                ('usuario_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_enviado'],
            },
        ),
    ]
