# Generated by Django 5.2.6 on 2025-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogeventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='resumen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
